name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
  # TODO
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0

      - run: echo $GITHUB_WORKSPACE
      - run: pwd
        working-directory: ${{ GITHUB_WORKSPACE }}
      - run: which npm
        working-directory: $GITHUB_WORKSPACE
      - run: which node
        working-directory: $GITHUB_WORKSPACE
      - run: ls
        working-directory: $GITHUB_WORKSPACE
      - run: pwd
        working-directory: $GITHUB_WORKSPACE

      - run: npm install --release
        working-directory: $GITHUB_WORKSPACE
      
      - run: npm run build
        working-directory: $GITHUB_WORKSPACE
      
      - name: Push build
        working-directory: $GITHUB_WORKSPACE
        run: |
          git checkout gh-pages
          mv dist/* .
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add --all
          git commit -m "Update on $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master
